### ISSUE TITLE
Todo List screen

### ISSUE THREAD

**Issue by octari** [studywithfly/StudyWithKitten#3]
- [ ] Create todo list screen

- [ ] Prompt user for a new task in the textbox

- [ ] Edit task in the detailed screen

- [ ] Delete button for removing the task

- [ ] Click to cross the task when it is completed
